export const INTEREST_TYPES = {
  SECTOR: "SECTOR",
  INDUSTRY: "INDUSTRY",
  COUNTRY: "COUNTRY",
  CUSTOM: "CUSTOM",
} as const;

export const SECTORS: string[] = [
  "Technology",
  "Financials",
  "Energy",
  "Industrials",
  "Health Care",
  "Consumer Discretionary",
  "Consumer Staples",
  "Utilities",
  "Real Estate",
  "Materials",
  "Communication Services",
];

export const INDUSTRIES_BY_SECTOR: Record<string, string[]> = {
  Technology: [
    "AI / Machine Learning",
    "Semiconductors",
    "Cloud / SaaS",
    "Cybersecurity",
    "Fintech Infrastructure",
    "Robotics",
    "Data Centers",
    "Consumer Electronics",
    "Developer Tools",
  ],
  Financials: [
    "Banking",
    "Insurance",
    "Asset Management",
    "Payments",
    "Capital Markets",
    "Wealth Management",
  ],
  Energy: [
    "Oil & Gas",
    "Renewables",
    "Battery Storage",
    "Nuclear",
    "Hydrogen",
    "Power Generation",
    "Energy Trading",
  ],
  Industrials: [
    "Aerospace & Defense",
    "Logistics",
    "Construction",
    "Manufacturing",
    "Automation",
    "Rail & Transit",
  ],
  "Health Care": [
    "Biotech",
    "Pharma",
    "Medical Devices",
    "HealthTech",
    "Diagnostics",
  ],
  "Consumer Discretionary": [
    "Automotive",
    "Luxury",
    "Travel",
    "E-commerce",
    "Gaming",
  ],
  "Consumer Staples": [
    "Food & Beverage",
    "Household Products",
    "Personal Care",
    "Retail Staples",
  ],
  Utilities: [
    "Electric Utilities",
    "Water Utilities",
    "Grid Infrastructure",
  ],
  "Real Estate": [
    "Residential",
    "Commercial",
    "REITs",
    "Hospitality",
    "Industrial Real Estate",
    "Dubai Real Estate",
  ],
  Materials: [
    "Mining",
    "Steel",
    "Chemicals",
    "Rare Earths",
  ],
  "Communication Services": [
    "Telecom",
    "Media",
    "Streaming",
    "Social Platforms",
    "AdTech",
  ],
};
