import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import registerRouter from "./register";
import profileRouter from "./profile";
import opportunitiesRouter from "./opportunities";
import forumsRouter from "./forums";
import interestsRouter from "./interests";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import usersRouter from "./users";
import hubsRouter from "./hubs";
import moneyManagementRouter from "./moneyManagement";
import followRouter from "./follow";
import conversationsRouter from "./conversations";
import reportsRouter from "./reports";
import pushTokensRouter from "./pushTokens";
import headlinesRouter from "./headlines";
import blocksRouter from "./blocks";
import overviewRouter from "./overview";
import adminSeedRouter from "./adminSeed";
import adminRouter from "./admin";
import userAccountRouter from "./userAccount";
import opportunityCommentsRouter from "./opportunityComments";
import portfolioAssetsRouter from "./portfolioAssets";
import searchRouter from "./search";
import savedSearchesRouter from "./savedSearches";
import discoveryRouter from "./discovery";
import passwordResetRouter from "./passwordReset";
import billingRouter from "./billing";
import savedArticlesRouter from "./savedArticles";
import insightsRouter from "./insights";
import adminHealthRouter from "./adminHealth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(registerRouter);
router.use(profileRouter);
router.use(opportunitiesRouter);
router.use(forumsRouter);
router.use(interestsRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(usersRouter);
router.use(hubsRouter);
router.use(moneyManagementRouter);
router.use(followRouter);
router.use(conversationsRouter);
router.use(reportsRouter);
router.use(pushTokensRouter);
router.use(headlinesRouter);
router.use(blocksRouter);
router.use(overviewRouter);
router.use(adminSeedRouter);
router.use(adminRouter);
router.use(userAccountRouter);
router.use("/opportunities", opportunityCommentsRouter);
router.use("/user/assets", portfolioAssetsRouter);
router.use("/search", searchRouter);
router.use("/user/saved-searches", savedSearchesRouter);
router.use(discoveryRouter);
router.use(passwordResetRouter);
router.use(billingRouter);
router.use(savedArticlesRouter);
router.use(insightsRouter);
router.use(adminHealthRouter);

export default router;
