const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0a0a0a",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#171717",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#171717",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#f5f5f5",
    accentForeground: "#171717",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
  },
  dark: {
    text: "#fafafa",
    tint: "#fafafa",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#141414",
    cardForeground: "#fafafa",
    primary: "#fafafa",
    primaryForeground: "#0a0a0a",
    secondary: "#1f1f1f",
    secondaryForeground: "#fafafa",
    muted: "#1f1f1f",
    mutedForeground: "#a3a3a3",
    accent: "#1f1f1f",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#262626",
    input: "#262626",
    success: "#22c55e",
    successForeground: "#000000",
    warning: "#f59e0b",
  },
  radius: 10,
};

export default colors;
